### ISSUE TITLE
Error Creating Graph!

### ISSUE THREAD

**Issue by pk8523** [p-alik/nfsen#12] opened 2018-12-05 19:31 UTC
I’m having an issue getting the graphs to show data.  In the live Profile on the details tab all graphs just show “Error Creating Graph!”.  I can’t seem to find any log file referencing any issues and I see data in Statistics Table and netflow processing.
Thanks

**Comment by p-alik** [comment] 2018-12-06 09:01
https://sourceforge.net/p/nfsen/mailman/message/36486692/

> Sounds like a permissions issue in your graphs/www data.

**Comment by pk8523** [comment] 2018-12-06 12:22
Any Idea what folder I’m looking for? Everything under /data/nfsen is owned by www-data with 0775 permissions including /data/nfsen/profiles-data/live and all sub folders.  Is there a different account that the graphs would be using to access the rrd files located there or is the permissions issue somewhere else that I’m not finding?

**Comment by pk8523** [comment] 2018-12-06 12:37
the /var/www/nfsen is owned by www-data with 0775 permissions.  Im not finding any directory that would indicate where the graphs are reading the data from other than /data/nfsen/profiles-data/live

**Comment by pk8523** [comment] 2018-12-07 13:08
I figured it out I named my router with dashes apparently that's a bad Idea.  I took the dashes out and the graphs are now showing data.

**Comment by luitzifa** [comment] 2019-09-11 11:39
I got the same error and my devices are named with dashes too. But for me this was not the cause of the problem. My problem was that i had a color with just 5 digits e.g. "#8f0e2".
After fixing the colors it works, also with dashes in my devicenames.

**Comment by p-alik** [comment] 2019-09-12 04:48
@pk8523, @luitzifa thanks to both of you for sharing your experienced solutions. If you have recommendation with regard to improvement, please share it. Otherwise I'll close the issue.

**Closed as completed** 2019-11-06 09:41 UTC
